### ISSUE TITLE
MOSFET Q

### ISSUE THREAD

**Issue by gcormier** [bretwatty/Arduino-8x-PCB-Smart-Charger-Discharger#3]
Just curious, how come you paired up the IRLML2502 with the IRLZ44N?

**Comment by brettwatty** [comment]
So you have the option to use SMD or THT components.

**Comment by gcormier** [comment]
Ah very cool. Power resistors the same idea?

**Comment by gcormier** [comment]
Nevermind - just saw that you are doubling up the power resistors. These are for detecting the current.
